AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NotifyCloudFormationResource

Parameters:
  NotifySlackUrl:
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  NotifyCloudFormationResourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notify-cloudformation-resource-function
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Timeout: 30
      Policies:
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
      Environment:
        Variables:
          NOTIFY_SLACK_URL: !Ref NotifySlackUrl
      Events:
        NotifySlack:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * MON *) # 日本時間で月曜日のAM9時

  NotifyCloudFormationResourceFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${NotifyCloudFormationResourceFunction}"
